version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      # Mount host directories for tool execution and data storage
      - /home/$USER/fuzzbench-data:/app/data
      - /usr/local/bin:/app/host-tools:ro
    privileged: true
    pid: host
    network_mode: host

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=devsec_scanner
      - POSTGRES_USER=devsec
      - POSTGRES_PASSWORD=secure_password_change_me
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/$USER/fuzzbench-data/db:/backup

  # ========================================
  # LOCAL DOCKER DEPLOYMENT CONFIGURATION
  # ========================================
  # Uncomment the services below for local development without host integration
  # Comment out the services above and uncomment these for standalone Docker deployment

  # app-local:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=5000
  #     - SESSION_SECRET=your-local-session-secret
  #     - DATABASE_URL=postgresql://localuser:localpass@postgres-local:5432/fuzzbranchdb
  #   depends_on:
  #     - postgres-local
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     # Local directories for development
  #     - ./data:/app/data
  #     - ./tools:/app/host-tools
  #   networks:
  #     - fuzz-network-local

  # postgres-local:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=fuzzbranchdb
  #     - POSTGRES_USER=localuser
  #     - POSTGRES_PASSWORD=localpass
  #   ports:
  #     - "5433:5432"  # Different port to avoid conflicts
  #   volumes:
  #     - postgres_data_local:/var/lib/postgresql/data
  #   networks:
  #     - fuzz-network-local

volumes:
  postgres_data:
  # postgres_data_local:  # Uncomment for local deployment

# networks:
#   fuzz-network-local:   # Uncomment for local deployment
#     driver: bridge