version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5050
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - ${HOME}/fuzzbench-data:/app/data
      - ${HOME}/devsec-tools:/app/tools
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${PGDATABASE:-devsec_scanner}
      - POSTGRES_USER=${PGUSER:-devsec}
      - POSTGRES_PASSWORD=${PGPASSWORD:-secure_password_change_me}
    ports:
      - "${PGPORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${HOME}/fuzzbench-data/db:/backup
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
