version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5050
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /home/vboxuser/fuzzbench-data:/app/data
      - /usr/local/bin:/app/host-tools:ro
      - /home/vboxuser/devsec-tools:/host/tools        # <--- ДОБАВИТЬ
    privileged: true
    pid: host
    network_mode: host

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=devsec_scanner
      - POSTGRES_USER=devsec
      - POSTGRES_PASSWORD=secure_password_change_me
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/vboxuser/fuzzbench-data/db:/backup

volumes:
  postgres_data:
